[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
chatbot = { path = "../chatbot" }
miniserve = { path = "../miniserve" }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
